"""pehla

Revision ID: 2e6bef0b4541
Revises: 
Create Date: 2021-11-08 15:34:46.266273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6bef0b4541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('Type', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'profile_pic')
    op.drop_column('movie', 'Type')
    # ### end Alembic commands ###
