"""empty message

Revision ID: 4806a403dd1f
Revises: 1a4ce8463b04
Create Date: 2022-01-06 15:25:16.655680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4806a403dd1f'
down_revision = '1a4ce8463b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('amount', sa.String(), nullable=True))
    op.add_column('order', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_status')
    op.drop_column('order', 'amount')
    # ### end Alembic commands ###
