"""Initial migration.

Revision ID: 5c9072687a10
Revises: d6f05c5d603d
Create Date: 2021-12-15 23:01:30.624980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9072687a10'
down_revision = 'd6f05c5d603d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_series', sa.Column('orignal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_series', 'orignal')
    # ### end Alembic commands ###
