"""empty message

Revision ID: 5ddb38af95db
Revises: 5c9072687a10
Create Date: 2021-12-20 15:32:56.006824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddb38af95db'
down_revision = '5c9072687a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_rj')
    op.drop_table('dataRCS')
    op.drop_table('data_rjs')
    op.drop_table('data_rjN')
    op.add_column('web_series', sa.Column('uid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'web_series', 'user_table', ['uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_series', type_='foreignkey')
    op.drop_column('web_series', 'uid')
    op.create_table('data_rjN',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"data_rjN_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mob', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_7', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_8', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_9', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_10', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_11', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dues', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('w_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('w_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grind', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cutter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_rjN_pkey')
    )
    op.create_table('data_rjs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mob', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_7', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_8', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_9', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dues', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('days', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_rjs_pkey')
    )
    op.create_table('dataRCS',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"dataRCS_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mob', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_7', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_8', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_9', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_10', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_11', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dues', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('w_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('w_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('grind', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cutter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dataRCS_pkey')
    )
    op.create_table('data_rj',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mob', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('final_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_5', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_6', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_7', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_8', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plate_9', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ch_4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dues', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_rj_pkey')
    )
    # ### end Alembic commands ###
