"""Orignals-fix

Revision ID: d6f05c5d603d
Revises: e534b06bfe87
Create Date: 2021-11-27 18:36:10.280878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f05c5d603d'
down_revision = 'e534b06bfe87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('orignal', sa.Integer(), nullable=True))
    op.add_column('season', sa.Column('orignal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season', 'orignal')
    op.drop_column('movie', 'orignal')
    # ### end Alembic commands ###
