"""Pehla

Revision ID: e534b06bfe87
Revises: bbb6ae63bc97
Create Date: 2021-11-10 13:57:07.466178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e534b06bfe87'
down_revision = 'bbb6ae63bc97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('short_description', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('web_series', sa.Column('short_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_series', 'short_description')
    op.drop_column('user_table', 'full_name')
    op.drop_column('movie', 'short_description')
    # ### end Alembic commands ###
